// Ciudades y localidades de Chile para los selectores de origen/destino
// de un viaje. No es exhaustiva (Chile tiene 346 comunas + miles de
// localidades) — son las capitales regionales, capitales provinciales y
// las ciudades/pueblos con más movimiento de carga. El selector permite
// escribir una que no esté en la lista.
//
// Ordenadas de norte a sur (útil para armar una ruta); el selector filtra
// por texto igual.

export const CIUDADES_CHILE: string[] = [
  // Arica y Parinacota / Tarapacá
  "Arica",
  "Putre",
  "Iquique",
  "Alto Hospicio",
  "Pozo Almonte",
  "Pica",
  "Huara",
  // Antofagasta
  "Tocopilla",
  "María Elena",
  "Calama",
  "San Pedro de Atacama",
  "Antofagasta",
  "Mejillones",
  "Baquedano",
  "Taltal",
  // Atacama
  "Chañaral",
  "Diego de Almagro",
  "El Salvador",
  "Copiapó",
  "Caldera",
  "Tierra Amarilla",
  "Vallenar",
  "Huasco",
  "Freirina",
  // Coquimbo
  "La Serena",
  "Coquimbo",
  "Andacollo",
  "Vicuña",
  "Ovalle",
  "Monte Patria",
  "Combarbalá",
  "Illapel",
  "Salamanca",
  "Los Vilos",
  "Canela",
  // Valparaíso
  "La Ligua",
  "Petorca",
  "Cabildo",
  "Papudo",
  "Zapallar",
  "Puchuncaví",
  "Quintero",
  "Concón",
  "Viña del Mar",
  "Valparaíso",
  "Quilpué",
  "Villa Alemana",
  "Limache",
  "Olmué",
  "Quillota",
  "La Calera",
  "La Cruz",
  "Nogales",
  "Hijuelas",
  "San Felipe",
  "Putaendo",
  "Santa María",
  "Llaillay",
  "Catemu",
  "Los Andes",
  "Calle Larga",
  "Rinconada",
  "San Esteban",
  "Casablanca",
  "Algarrobo",
  "El Quisco",
  "El Tabo",
  "Cartagena",
  "San Antonio",
  "Santo Domingo",
  "Isla de Pascua",
  // Metropolitana de Santiago
  "Santiago",
  "Colina",
  "Lampa",
  "Til Til",
  "Batuco",
  "Quilicura",
  "Pudahuel",
  "Maipú",
  "Cerrillos",
  "Estación Central",
  "Puente Alto",
  "San Bernardo",
  "Buin",
  "Paine",
  "Calera de Tango",
  "Talagante",
  "Peñaflor",
  "El Monte",
  "Isla de Maipo",
  "Melipilla",
  "María Pinto",
  "Curacaví",
  "Alhué",
  "Pirque",
  "San José de Maipo",
  // O'Higgins
  "Rancagua",
  "Machalí",
  "Graneros",
  "Mostazal",
  "Codegua",
  "Doñihue",
  "Coltauco",
  "Rengo",
  "Requínoa",
  "Malloa",
  "Quinta de Tilcoco",
  "San Vicente de Tagua Tagua",
  "Peumo",
  "Las Cabras",
  "Pichidegua",
  "San Fernando",
  "Chimbarongo",
  "Nancagua",
  "Santa Cruz",
  "Palmilla",
  "Peralillo",
  "Chépica",
  "Lolol",
  "Pichilemu",
  "Marchigüe",
  "La Estrella",
  "Litueche",
  "Navidad",
  // Maule
  "Curicó",
  "Teno",
  "Romeral",
  "Molina",
  "Sagrada Familia",
  "Hualañé",
  "Licantén",
  "Vichuquén",
  "Rauco",
  "Talca",
  "San Clemente",
  "Pencahue",
  "Maule",
  "San Rafael",
  "Pelarco",
  "Río Claro",
  "Curepto",
  "Constitución",
  "Empedrado",
  "Linares",
  "Colbún",
  "Yerbas Buenas",
  "Villa Alegre",
  "San Javier",
  "Longaví",
  "Retiro",
  "Parral",
  "Cauquenes",
  "Chanco",
  "Pelluhue",
  // Ñuble
  "Chillán",
  "Chillán Viejo",
  "Bulnes",
  "Quillón",
  "San Carlos",
  "Ñiquén",
  "San Fabián",
  "Coihueco",
  "Pinto",
  "El Carmen",
  "Pemuco",
  "Yungay",
  "Quirihue",
  "Cobquecura",
  "Ninhue",
  "Portezuelo",
  "Coelemu",
  "San Nicolás",
  // Biobío
  "Los Ángeles",
  "Cabrero",
  "Yumbel",
  "Laja",
  "San Rosendo",
  "Nacimiento",
  "Negrete",
  "Mulchén",
  "Quilleco",
  "Santa Bárbara",
  "Antuco",
  "Tucapel",
  "Concepción",
  "Talcahuano",
  "Hualpén",
  "San Pedro de la Paz",
  "Chiguayante",
  "Penco",
  "Tomé",
  "Coronel",
  "Lota",
  "Santa Juana",
  "Hualqui",
  "Florida",
  "Lebu",
  "Arauco",
  "Curanilahue",
  "Los Álamos",
  "Cañete",
  "Contulmo",
  "Tirúa",
  // La Araucanía
  "Angol",
  "Renaico",
  "Collipulli",
  "Ercilla",
  "Los Sauces",
  "Purén",
  "Lumaco",
  "Traiguén",
  "Victoria",
  "Curacautín",
  "Lonquimay",
  "Temuco",
  "Padre Las Casas",
  "Lautaro",
  "Perquenco",
  "Vilcún",
  "Freire",
  "Pitrufquén",
  "Gorbea",
  "Loncoche",
  "Villarrica",
  "Pucón",
  "Cunco",
  "Melipeuco",
  "Nueva Imperial",
  "Carahue",
  "Puerto Saavedra",
  "Teodoro Schmidt",
  "Toltén",
  "Cholchol",
  "Galvarino",
  "Lican Ray",
  // Los Ríos
  "Valdivia",
  "Corral",
  "Mariquina",
  "San José de la Mariquina",
  "Lanco",
  "Máfil",
  "Los Lagos",
  "Panguipulli",
  "Paillaco",
  "La Unión",
  "Río Bueno",
  "Lago Ranco",
  "Futrono",
  // Los Lagos
  "Osorno",
  "San Pablo",
  "Puyehue",
  "Entre Lagos",
  "Río Negro",
  "Purranque",
  "Puerto Octay",
  "Puerto Varas",
  "Llanquihue",
  "Frutillar",
  "Fresia",
  "Los Muermos",
  "Puerto Montt",
  "Puerto Chacabuco",
  "Calbuco",
  "Maullín",
  "Cochamó",
  "Hornopirén",
  "Castro",
  "Ancud",
  "Quellón",
  "Dalcahue",
  "Chonchi",
  "Quemchi",
  "Quinchao",
  "Achao",
  "Chaitén",
  "Futaleufú",
  "Palena",
  // Aysén
  "Coyhaique",
  "Puerto Aysén",
  "Chile Chico",
  "Cochrane",
  "Puerto Cisnes",
  "La Junta",
  "Villa O'Higgins",
  "Balmaceda",
  // Magallanes
  "Puerto Natales",
  "Punta Arenas",
  "Porvenir",
  "Puerto Williams",
  "Cerro Castillo",
];
